# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: café-do | design, web, e fortalecimento de marca
email: contato@cafe-do.com
description: > # '>' means to ignore newlines until the next property
  Design, web, e fortalecimento de marca.
  Extraímos o melhor de cada projeto, colaborando com criatividade para aumentar 
  a visibilidade no mercado e as vendas de nossos clientes, na internet e fora dela.
# Onde há café há criatividade
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cafe-do.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: :compressed
